modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: ip4

  http_api:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]
      method: GET
      follow_redirects: true
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: ip4

  http_auth:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 401]
      method: GET
      follow_redirects: true
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: ip4

  dns_apex:
    prober: dns
    timeout: 5s
    dns:
      query_name: eastlakewolfpack.org
      query_type: A
      transport_protocol: udp
      preferred_ip_protocol: ip4

  dns_www:
    prober: dns
    timeout: 5s
    dns:
      query_name: www.eastlakewolfpack.org
      query_type: A
      transport_protocol: udp
      preferred_ip_protocol: ip4
